### ISSUE TITLE
Building with Intel Compiler

### ISSUE THREAD

**Issue by WhoWouldaThunk** [greg7mdp/parallel-hashmap#9] opened 2019-05-10 18:31 UTC
C++ isn't my strong suit so I haven't quite figured out what this issue is yet. 
But, when I try to build the example in MSVS 2017 and 2019 with Windows SDK 10.0.17763.0, using ICC 2019 update 3 (all are debug builds using default settings), I get these errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	#3466	inheriting constructors must be inherited from a direct base class	hash	d:\Downloads\parallel-hashmap-master\parallel_hashmap\phmap.h	4144	
Error (active)	E1389	redeclaration cannot add dllexport/dllimport to "ldexpf" (declared at line 706 of "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\corecrt_math.h")	hash	C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2019\windows\compiler\include\math.h	704	
Error (active)	E1389	redeclaration cannot add dllexport/dllimport to "powf" (declared at line 743 of "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\corecrt_math.h")	hash	C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2019\windows\compiler\include\math.h	799	
Error (active)	E2512	the argument to a feature-test macro must be a simple identifier	hash	D:\Downloads\parallel-hashmap-master\parallel_hashmap\phmap_config.h	557	
Error (active)	E2512	the argument to a feature-test macro must be a simple identifier	hash	D:\Downloads\parallel-hashmap-master\parallel_hashmap\phmap_config.h	573	
Error (active)	E2512	the argument to a feature-test macro must be a simple identifier	hash	D:\Downloads\parallel-hashmap-master\parallel_hashmap\phmap_config.h	604	
Error	#3466	inheriting constructors must be inherited from a direct base class	hash	d:\Downloads\parallel-hashmap-master\parallel_hashmap\phmap.h	2166	
Error	#3466	inheriting constructors must be inherited from a direct base class	hash	d:\Downloads\parallel-hashmap-master\parallel_hashmap\phmap.h	3304	
Error	#3466	inheriting constructors must be inherited from a direct base class	hash	d:\Downloads\parallel-hashmap-master\parallel_hashmap\phmap.h	4203	
Error	#3466	inheriting constructors must be inherited from a direct base class	hash	d:\Downloads\parallel-hashmap-master\parallel_hashmap\phmap.h	4262	
Error	#3466	inheriting constructors must be inherited from a direct base class	hash	d:\Downloads\parallel-hashmap-master\parallel_hashmap\phmap.h	4321	
Error	#3466	inheriting constructors must be inherited from a direct base class	hash	d:\Downloads\parallel-hashmap-master\parallel_hashmap\phmap.h	4372	
Error	#3466	inheriting constructors must be inherited from a direct base class	hash	d:\Downloads\parallel-hashmap-master\parallel_hashmap\phmap.h	4419	
Error	#3466	inheriting constructors must be inherited from a direct base class	hash	d:\Downloads\parallel-hashmap-master\parallel_hashmap\phmap.h	4470	
Error	#3466	inheriting constructors must be inherited from a direct base class	hash	d:\Downloads\parallel-hashmap-master\parallel_hashmap\phmap.h	4520	

Works fine with Clang and MSVC using c++14 standard though. 

Under c++17 with Clang I get:

Error (active)	E2512	the argument to a feature-test macro must be a simple identifier	hash	D:\Downloads\parallel-hashmap-master\parallel_hashmap\phmap_config.h	557	
Error (active)	E2512	the argument to a feature-test macro must be a simple identifier	hash	D:\Downloads\parallel-hashmap-master\parallel_hashmap\phmap_config.h	573	
Error (active)	E2512	the argument to a feature-test macro must be a simple identifier	hash	D:\Downloads\parallel-hashmap-master\parallel_hashmap\phmap_config.h	604	
Error		cannot convert 'const std::basic_string_view<char, std::char_traits<char> >' to 'size_t' (aka 'unsigned int') without a conversion operator	hash	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xhash	31

And with MSVC

Error (active)	E2512	the argument to a feature-test macro must be a simple identifier	hash	D:\Downloads\parallel-hashmap-master\parallel_hashmap\phmap_config.h	557	
Error (active)	E2512	the argument to a feature-test macro must be a simple identifier	hash	D:\Downloads\parallel-hashmap-master\parallel_hashmap\phmap_config.h	573	
Error (active)	E2512	the argument to a feature-test macro must be a simple identifier	hash	D:\Downloads\parallel-hashmap-master\parallel_hashmap\phmap_config.h	604	

Though you might want to know.

Cheers

**Comment by greg7mdp** [comment] 2019-05-11 00:40
Hi @WhoWouldaThunk,

Thanks a lot for the report. I don't have access to the intel compiler (I assume that is what ICC 2019 is), but I checked in a new version which should resolve some issues. Could you give it a try?

Thanks!

**Comment by greg7mdp** [comment] 2019-05-12 23:54
Hi @WhoWouldaThunk , I believe the issue is fixed now. Please let me know how it works for you.
Thanks - greg

**Closed** 2019-05-13 11:28 UTC

**Comment by WhoWouldaThunk** [comment] 2019-05-13 15:44
Hey Greg, 

Excellent work! Builds find now and seems to work properly with one, sole, exception:

It seems that(at least for flat_hash_map and set) need to be initialized with a minimum of 1 value.
So:
	phmap::flat_hash_map<std::string, std::string> email = {{ "tom",  "tom@gmail.com"}}
builds and works perfectly fine.

But:
	phmap::flat_hash_map<std::string, std::string> email;

results in the following build error(although clang and msvc work properly):

assertion failed at: "shared/cfe/edgcpfe/lower_init.c", line 7013	parallel_hashmap\phmap.h	line 992.

**Comment by greg7mdp** [comment] 2019-05-13 17:22
What compiler are you using? this does compile fine for me with Intel C++
19.0
 
greg

  _____

**Comment by greg7mdp** [comment] 2019-05-13 17:30
I am using Intel Parallel Studio XE 2019 Update 3.

  _____

**Comment by WhoWouldaThunk** [comment] 2019-05-13 21:01
Same version as you are ostensibly: 2019.0.3.056.

I'll re-install mine and see if that does anything.

**Comment by greg7mdp** [comment] 2019-05-13 21:17
I was building from VS 2015 in case that makes a difference.

  _____

**Comment by WhoWouldaThunk** [comment] 2019-05-13 22:24
Well, still that issue after reinstalling ICC 2019. Even ran it from the command line to avoid any potential MSVS issues, and it was throwing that error.
I had ICC 2018 update 4 on my hd, so I installed that version and it ran fine in vs 2017.

I'll try another workstation tomorrow with 2019 update 3 and see if I can narrow down where this issue stems from. Might just be god knows what on my computer interfering somehow.

**Comment by greg7mdp** [comment] 2019-05-13 23:34
It is not just your computer, I see someone reported that issue to Intel:
<https://software.intel.com/en-us/forums/intel-c-compiler/topic/809169>
https://software.intel.com/en-us/forums/intel-c-compiler/topic/809169
 
It looks like the compiler itself is throwing an assertion  (assertion
failed at: "shared/cfe/edgcpfe/lower_init.c", line 7013). Because we don't
have the source code it may not be easy to figure out what causes this. 
 
Can you email me the program that crashes the compiler. I did remove the
initialization in the basic.cc example, but maybe there is a subtle
difference that causes this compiler issue?
 
Thanks,
 
greg

  _____

**Comment by WhoWouldaThunk** [comment] 2019-05-13 23:44
Interesting. I tried it on a couple different machines with ICC 2019 update 1 and update 3 and they both have this issue. I don't have update 2 kicking around anymore, but I imagine it's the same. Quite possibly some change they made between 2018 update 4 and the 2019 update 1 release. 

Here's the testcase I'm using:

#include <d:\Downloads\parallel-hashmap-master\parallel_hashmap\phmap.h>
using phmap::flat_hash_map;

int main()
{
	flat_hash_map<std::string, std::string> email;

	return 0;
}

**Comment by greg7mdp** [comment] 2019-05-14 11:46
OK, I figured out that the compiler crash is caused by the CompressedTuple
class. Try the attached phmap.h, should work fine and the only issue is that
the map object itself may be a few bytes larger.
 
Thanks,
 
greg

  _____

**Comment by greg7mdp** [comment] 2019-05-14 11:47
btw I installed the latest Intel Visual Studio on anothe computer (with
visual studio 2017) and I was able to reproduce the issue.

  _____

**Comment by WhoWouldaThunk** [comment] 2019-05-14 18:23
What a weird error. Works with ICC 2019 on VS 2015, but not on VS 2017+, unless you use ICC < 2019.

I think you might need to upload the latest phmap.h file as I'm guessing the posts here have a line or character limit as seems to be about 1/3 the size of the actual file where it cuts off.

**Comment by greg7mdp** [comment] 2019-05-14 18:38
I have added the file in a gist:
<https://gist.github.com/greg7mdp/3156fb43b1b523065edfe8e663cf35d8>
https://gist.github.com/greg7mdp/3156fb43b1b523065edfe8e663cf35d8
 
greg

  _____

**Comment by WhoWouldaThunk** [comment] 2019-05-14 21:36
That fix in the compressedtuple class seems to have done the trick. Excellent work! Tested it on ICC 2018 update 4, 2019 update 1 and 3, Clang 8 & 9, and MSVC v141 & v142 and everything is as should be. 
Much appreciated! The library and your timely fix on this.

**Comment by greg7mdp** [comment] 2019-05-14 23:00
Thanks for the kind words and the thorough testing. I'll push a fix in this github repository within a couple days. I'll see if I can figure out a way to still use the compressed tuple with the Intel compiler.

**Comment by greg7mdp** [comment] 2019-05-15 13:00
Hi there, I just updated the github repository with the fix.
