### ISSUE TITLE
Include flags to own headers are not passed correctly during the build

### ISSUE THREAD

**Issue by barracuda156** [greg7mdp/parallel-hashmap#191] opened 2023-05-16 10:37 UTC
```
[ 22%] Building CXX object CMakeFiles/test_flat_hash_set.dir/tests/flat_hash_set_test.cc.o
/opt/local/bin/g++-mp-12   -pipe -Os -DNDEBUG -I/opt/local/include -D_GLIBCXX_USE_CXX11_ABI=0 -arch ppc -mmacosx-version-min=10.6 -MD -MT CMakeFiles/test_flat_hash_map.dir/tests/flat_hash_map_test.cc.o -MF CMakeFiles/test_flat_hash_map.dir/tests/flat_hash_map_test.cc.o.d -o CMakeFiles/test_flat_hash_map.dir/tests/flat_hash_map_test.cc.o -c /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_parallel-hashmap/parallel-hashmap/work/parallel-hashmap-1.3.11/tests/flat_hash_map_test.cc
/opt/local/bin/g++-mp-12   -pipe -Os -DNDEBUG -I/opt/local/include -D_GLIBCXX_USE_CXX11_ABI=0 -arch ppc -mmacosx-version-min=10.6 -DUNORDERED_SET_CXX17 -MD -MT CMakeFiles/test_flat_hash_set.dir/tests/flat_hash_set_test.cc.o -MF CMakeFiles/test_flat_hash_set.dir/tests/flat_hash_set_test.cc.o.d -o CMakeFiles/test_flat_hash_set.dir/tests/flat_hash_set_test.cc.o -c /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_parallel-hashmap/parallel-hashmap/work/parallel-hashmap-1.3.11/tests/flat_hash_set_test.cc
/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_parallel-hashmap/parallel-hashmap/work/parallel-hashmap-1.3.11/tests/hash_policy_testing_test.cc:15:10: fatal error: parallel_hashmap/phmap.h: No such file or directory
   15 | #include "parallel_hashmap/phmap.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/test_hash_policy_testing.dir/tests/hash_policy_testing_test.cc.o] Error 1
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_parallel-hashmap/parallel-hashmap/work/build'
make[1]: *** [CMakeFiles/test_hash_policy_testing.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_parallel-hashmap/parallel-hashmap/work/parallel-hashmap-1.3.11/tests/flat_hash_set_test.cc:20:10: fatal error: parallel_hashmap/phmap.h: No such file or directory
   20 | #include "parallel_hashmap/phmap.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_parallel-hashmap/parallel-hashmap/work/parallel-hashmap-1.3.11/tests/compressed_tuple_test.cc:15:10: fatal error: parallel_hashmap/phmap.h: No such file or directory
   15 | #include "parallel_hashmap/phmap.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/test_flat_hash_set.dir/tests/flat_hash_set_test.cc.o] Error 1
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_parallel-hashmap/parallel-hashmap/work/build'
make[1]: *** [CMakeFiles/test_flat_hash_set.dir/all] Error 2
/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_parallel-hashmap/parallel-hashmap/work/parallel-hashmap-1.3.11/tests/flat_hash_map_test.cc:29:10: fatal error: parallel_hashmap/phmap.h: No such file or directory
   29 | #include "parallel_hashmap/phmap.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_parallel-hashmap/parallel-hashmap/work/parallel-hashmap-1.3.11/tests/raw_hash_set_test.cc:18:10: fatal error: parallel_hashmap/phmap.h: No such file or directory
   18 | #include "parallel_hashmap/phmap.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
compilation terminated.
```

**Comment by greg7mdp** [comment] 2023-05-16 13:54
Is this still an issue?

**Comment by barracuda156** [comment] 2023-05-16 16:02
From the piece of log above (I am away from the machine now, can generate a full log tomorrow, if that is needed) it is seen that headers are not found, and that happens because CMake does not pass needed flags. From memory, that is set via target_include_directories
in CMakeLists.
If CMake build is properly specified, it just works in Macports, no manual fixed needed. Here it did not, and I had to add cxxflag with the path to folder with headers (in sources directory).

**Comment by greg7mdp** [comment] 2023-05-16 16:17
Thanks, I'm just wondering how you generated the project you are building? Normally running cmake should work, although I'm not familiar with macports.

**Comment by barracuda156** [comment] 2023-05-17 02:34
> Thanks, I'm just wondering how you generated the project you are building? Normally running cmake should work, although I'm not familiar with macports.

Portfile: https://github.com/macports/macports-ports/commit/15e7f0224ebc7e6bc5740db67eb62193920b0443
Should be installable with `sudo port -v -s install parallel-hash` (`-s` to build from source).

**Comment by greg7mdp** [comment] 2023-05-17 02:53
Does the portfile work as is with `configure.cxxflags-append  -I${worksrcpath}`?
If you want I can create a new release so you don't have to do the patches.

**Comment by greg7mdp** [comment] 2023-05-17 02:55
I think possibly the issue with the includes is that they are not in the standard location, they should be in `include/parallel-hashmap`, but they are directly in  `parallel-hashmap`.

**Comment by barracuda156** [comment] 2023-05-17 06:52
> I think possibly the issue with the includes is that they are not in the standard location, they should be in `include/parallel-hashmap`, but they are directly in `parallel-hashmap`.

Not sure, but possibly. In any case, regardless of where headers get installed, during the build CMake should pass a flag to include headers from the extracted sources. Something to keep in mind: by default, I think, CMake builds in an external dir. (This can be overridden if necessary.)

**Comment by greg7mdp** [comment] 2023-05-17 11:40
I think I know what the problem is. In your system, were the headers installed in `/opt/local/`? So for example there is `/opt/local/paralllel-hashmap/phmap.h`?

**Comment by greg7mdp** [comment] 2023-05-18 12:08
Well the compilation command (failing) showed that we were adding `/opt/local/include` to the include path.
`/opt/local/bin/g++-mp-12   -pipe -Os -DNDEBUG -I/opt/local/include ...`

**Comment by greg7mdp** [comment] 2023-05-22 21:50
Closing now, please reopen if you have more information of a suggestion for a change.

**Closed by greg7mdp** 2023-05-22 21:50 UTC
