### ISSUE TITLE
flat_hash_map sometimes gets corrupted

### ISSUE THREAD

**Issue by TylerGlaiel** [greg7mdp/parallel-hashmap#157] opened 2022-07-19 03:43 UTC
hash map of the format:
`phmap::flat_hash_map<std::string, std::vector<std::string>> mymap;`

with a map in this format, OCCASIONALLY doing
`mymap["Bar"] = mymap["Foo"];`
(where "Bar" does not yet exist in the hash map, but "Foo" does) results in mymap["Bar"] getting assigned an empty vector instead of the one that is stored at Foo. This happens in both debug AND release builds (MSVC)

This behavior is not seen when using std::unordered_map instead

(assigning to an intermediate value works properly however,
```
auto temp = mymap["Foo"];
mymap["Bar"] = temp;
```
)

**Comment by TylerGlaiel** [comment] 2022-07-19 18:55
Isolated a reproduction of the bug out of my project, here you go

```
#include <vector>
#include <string>
#include <iostream>
#include "phmap/phmap.h"


int main() {
    phmap::flat_hash_map<std::string, std::vector<std::string>> mymap;

    //initialize mymap
    mymap["hitF"].push_back("hitF");
    mymap["hitB"].push_back("hitB");
    mymap["idleF"].push_back("idleF");
    mymap["idleB"].push_back("idleB");
    mymap["walkF"].push_back("walkF");
    mymap["walkB"].push_back("walkB");
    mymap["dyingF"].push_back("dyingF");
    mymap["dyingB"].push_back("dyingB");
    mymap["attackF"].push_back("attackF");
    mymap["attackB"].push_back("attackB");

    //set fallbacks
    mymap["downB"] = mymap["idleB"];
    mymap["downF"] = mymap["idleF"];
    mymap["hit_upF"] = mymap["idleF"];
    mymap["hit_upB"] = mymap["idleB"];
    mymap["weakF"] = mymap["idleF"];
    mymap["weakB"] = mymap["idleB"];

    //print map
    for(auto& element : mymap) {
        std::cout << element.first << ": ";
        for(auto& inner : element.second) {
            std::cout << inner;
        }
        std::cout << std::endl;
    }


    return 0;
}

```

outputs:
```
hitF: hitF
hitB: hitB
idleF: idleF
idleB: idleB
weakF:
walkF: walkF
weakB: idleB
walkB: walkB
downB: idleB
hit_upF: idleF
downF: idleF
hit_upB: idleB
dyingF: dyingF
dyingB: dyingB
attackB: attackB
attackF: attackF
```

notice that "weakF" is missing its data

**Comment by greg7mdp** [comment] 2022-07-19 19:07
Super cool, thanks a lot @TylerGlaiel this is a great help!

**Comment by greg7mdp** [comment] 2022-07-20 00:55
Hi @TylerGlaiel ,

Unfortunately, this is not a bug, but an artifact of the fact that the `flat` maps `operator[]` returns references, which are invalidated when the hash map (a memory array) resizes.

This is what happens here. `mymap["idleF"]` returns a reference to the correct vector, but when inserting the new key `weakF` (when `mymap["weakF"]` is evaluated), the hash map array resizes, and the reference becomes invalid.

So this cannot be fixed for the flat_hash_map. You could use a `phmap::node_hash_map` which will work fine.

Closing the issue. Fell free to comment or reopen if you have more questions.

**Closed by greg7mdp** 2022-07-20 00:55 UTC
