### ISSUE TITLE
 error: 'ptr' was not declared in this scope

### ISSUE THREAD

**Issue by HBSDLJZ** [greg7mdp/parallel-hashmap#148] opened 2022-06-16 06:13 UTC
![image](https://user-images.githubusercontent.com/43542395/174003574-de34925e-94b4-4d2a-b32f-c53d02c0c6b0.png)
![image](https://user-images.githubusercontent.com/43542395/174003607-3d0907d3-de6b-4cfb-8302-534167e50b3d.png)
How can I solve the problems?Thank you!

**Comment by HBSDLJZ** [comment] 2022-06-16 06:17
![image](https://user-images.githubusercontent.com/43542395/174004216-00195eb0-9d73-4505-a650-6fbd3e81fa7a.png)

**Comment by greg7mdp** [comment] 2022-06-21 01:29
The issue is that the lambda passed to `if_contains` takes a `map::value_type&` argument. This has changed a little while ago.
See examples in `tests/parallel_hash_map_test.cc`.

**Comment by greg7mdp** [comment] 2022-06-21 01:29
I will close the issue. Please reopen if needed. Thanks!

**Closed by greg7mdp** 2022-06-21 01:29 UTC
